{% set name = "labellib" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  entry_points:
    - labellib = labellib:main

requirements:
  build:
    - python
    - setuptools
    - pip
    - cmake
    - ninja
    - pybind11
    - numpy
  host:
    - python
    - numpy
  run:
    - numpy

test:
  imports:
    - labellib

about:
  home: https://github.com/Fluorescence-Tools/LabelLib
  license: MPL-2.0
  summary: Python bindings for LabelLib

extra:
  recipe-maintainers:
    - tpeulen
  channels:
    - conda-forge