{% set name = "labellib" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -v"

requirements:
  build:
    - {{ compiler('cxx') }}
    - python
    - cmake
    - ninja
    - pybind11
    - numpy
  host:
    - python
    - pip
    - numpy
  run:
    - numpy

test:
  imports:
    - labellib

about:
  home: https://github.com/Fluorescence-Tools/LabelLib
  license: MPL-2.0
  summary: Python bindings for LabelLib

extra:
  recipe-maintainers:
    - tpeulen