sudo: false
language: cpp
python:
  - "2.7"
  - "3.7"
compiler:
  - clang
  - gcc
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - csh
    - python-numpy
    - libboost-dev
    - libeigen3-dev
    - g++
    - clang

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install md5sha1sum; fi
#- source devtools/travis-ci/install_miniconda.sh
#- conda config --add channels omnia
#- conda config --add channels conda-forge # hightest priority

script:
  mkdir build && cd build && cmake .. && make

