language: cpp
os: linux
dist: focal
  
jobs:
  include:
    - name: Linux
      stage: make
      services: docker
      script: docker run --rm -v ${TRAVIS_BUILD_DIR}:/io:rw -w="/io" quay.io/pypa/manylinux1_x86_64 /io/build_linux.sh
      workspaces:
        create:
          name: linux
          paths: wheelhouse
    - name: macOS-python2
      stage: make
      os: osx
      env: PYTHON=2.7
      compiler: clang
      install: pyenv install -s 3.7-dev
      script: ./build_osx.sh
    - name: macOS-python3
      stage: make
      os: osx
      env: PYTHON=3.7
      compiler: clang
      install: pyenv install -s 3.7-dev
      script: ./build_osx.sh
    - name: Windows
      stage: make
      os: windows
      language: sh
      script: ./build_win.sh
      workspaces:
        create:
          name: windows
          paths: C:/wheelhouse
    - name: deploy pypi
      stage: deploy
      services: docker
      workspaces:
        use:
          - linux
          - windows
      script: 
        - mv C:/wheelhouse/* wheelhouse/
        - docker run --rm -e PYPI_USER -e PYPI_PASS -v ${TRAVIS_BUILD_DIR}:/io:rw -w="/io" quay.io/pypa/manylinux1_x86_64 /io/pypi_upload.sh

stages:
    - make
    - name: deploy
      if: tag IS present
