sudo: required
language: cpp
dist: focal

homebrew_addons:
    addons: &homebrew
        packages:
            - md5sha1sum
        update: true
    
jobs:
  include:
    - name: Ubuntu-python2-make
      stage: make
      services: docker
      script: 
        - docker run --rm -e PYPI_USER -v ${TRAVIS_BUILD_DIR}:/io:rw -w="/io" quay.io/pypa/manylinux1_x86_64 /io/build-wheels.sh 2
        - ls wheels
    - name: Ubuntu-python3-make
      stage: make
      services: docker
      script: docker run --rm -v ${TRAVIS_BUILD_DIR}:/io:rw -w="/io" quay.io/pypa/manylinux1_x86_64 /io/build-wheels.sh 3
    - name: macOS-python2-make
      stage: make
      os: osx
      env: PYTHON=2.7
      compiler: clang
      addons: *homebrew
      install: pyenv install -s 3.7-dev
      script: ./make_osx.sh
    - name: macOS-python3
      stage: make
      os: osx
      env: PYTHON=3.7
      compiler: clang
      addons: *homebrew
      install: pyenv install -s 3.7-dev
      script: ./make_osx.sh
    - name: deploy pypi
      stage: deploy
      services: docker
      script: docker run --rm -v ${TRAVIS_BUILD_DIR}:/io:rw quay.io/pypa/manylinux1_x86_64 /io/pypi-upload.sh

stages:
    - make
    - name: deploy
      on:
        branch: master
        tags: true
