# cibuildwheel.toml
[build]
cp312-manylinux2014_x86_64 = "python -m pip install cmake"
cp312-macosx_arm64 = ""
cp312-macosx_x86_64 = ""
cp312-win_amd64 = ""

[options]
manylinux-image = "manylinux2014"
macos-deployment-target = "11.0"